//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioStationGlossary.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioStationGlossary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   用語検索ツール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item000 {
            get {
                return ResourceManager.GetString("item000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＤＢ検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item001 {
            get {
                return ResourceManager.GetString("item001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＤＢ登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item002 {
            get {
                return ResourceManager.GetString("item002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item003 {
            get {
                return ResourceManager.GetString("item003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内容 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item004 {
            get {
                return ResourceManager.GetString("item004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item005 {
            get {
                return ResourceManager.GetString("item005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像データ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item006 {
            get {
                return ResourceManager.GetString("item006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索文字列(前部分一致) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item101 {
            get {
                return ResourceManager.GetString("item101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item102 {
            get {
                return ResourceManager.GetString("item102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   昇順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item103 {
            get {
                return ResourceManager.GetString("item103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   降順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item104 {
            get {
                return ResourceManager.GetString("item104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された項目の編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item105 {
            get {
                return ResourceManager.GetString("item105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＤＢ書込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item201 {
            get {
                return ResourceManager.GetString("item201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item202 {
            get {
                return ResourceManager.GetString("item202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＤＢ読出し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item203 {
            get {
                return ResourceManager.GetString("item203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＤＢ削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string item204 {
            get {
                return ResourceManager.GetString("item204", resourceCulture);
            }
        }
    }
}
